#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#  ref: https://github.com/holman/dotfiles/blob/master/functions/c

cd "$PROJECTS/$1"
