
source $ZSH/zsh/brew.export.zsh
source $ZSH/config/go.path.zsh
source $ZSH/config/homebrew.path.zsh
source $ZSH/config/java.path.zsh
source $ZSH/config/nvm.path.zsh
source $ZSH/config/python.path.zsh
source $ZSH/config/rust.path.zsh
source $ZSH/config/system.path.zsh
source $ZSH/config/yarn.path.zsh
source $ZSH/config/database.alias.zsh
source $ZSH/config/docker.alias.zsh
source $ZSH/config/git.alias.zsh
source $ZSH/config/node.alias.zsh
source $ZSH/config/npm.alias.zsh
source $ZSH/config/ruby.alias.zsh
source $ZSH/config/system.alias.zsh
source $ZSH/config/system.env.zsh
source $ZSH/config/system.grc.zsh
source $ZSH/config/system.keys.zsh
source $ZSH/config/xcode.alias.zsh
source $ZSH/config/yarn.alias.zsh
source $ZSH/config/zsh.alias.zsh
source $ZSH/symlinks/rbenv.zsh
source $ZSH/zsh/config.zsh
source $ZSH/zsh/fpath.zsh
source $ZSH/zsh/prompt.zsh
autoload -Uz compinit && compinit
source $ZSH/config/git.completion.zsh
source $ZSH/config/nvm.completion.zsh
source $ZSH/config/ruby.completion.zsh
source $ZSH/config/zsh.completion.zsh
